[package]
name = "someval"
description = "Groups of optional values where at least one value is present"
repository = "https://github.com/nathan-at-least/someval.git"
version = "0.1.0"
edition = "2021"
license = "MIT"
